### PR TITLE
Fix: on PUT /properties, detect a duplicate property differing only by a trailing whitespace - fix #836

### LINKED ISSUE #836: Lors d'un PUT /properties, on ne détecte pas comme invalide lorsqu'une propriété est mentionné une 2e fois avec un espace à la fin

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

File: core/application/src/main/java/org/hesperides/core/application/platforms/PlatformUseCases.java [hunk 1]
```diff
@@ -573,9 +573,10 @@ public void purgeUnusedProperties(Platform.Key platformKey, String propertiesPat
     }
 
     private static boolean containsDuplicateKeys(List<AbstractValuedProperty> list) {
-        return !CollectionUtils.isEmpty(list) && !list.stream()
+        return list.stream()
                 .map(AbstractValuedProperty::getName)
-                .allMatch(new HashSet<>()::add);
+                .map(StringUtils::trim)
+                .collect(Collectors.toSet()).size() != list.size();
```
Comment (thomaslhostis) [inline core/application/src/main/java/org/hesperides/core/application/platforms/PlatformUseCases.java]: 👍

File: tests/bdd/src/test/resources/platforms/properties/save-properties.feature [hunk 2]
```diff
@@ -145,4 +145,11 @@ Feature: Save properties the old way
...
-    Then the request is rejected with a bad request error
\ No newline at end of file
+    Then the request is rejected with a bad request error
+
+  #issue-836
+  Scenario: save a duplicate property that only differ by a trailing whitespace
+    Given an existing module
+    And an existing platform with this module
+    When I try to save a duplicate property that only differ by a trailing whitespace
+    Then the request is rejected with a bad request error
```
Comment (thomaslhostis) [inline tests/bdd/src/test/resources/platforms/properties/save-properties.feature]: 👍 👍
